name: Debian 10 VM Workflow
on: [workflow_dispatch]
jobs:
  vm:
    runs-on: ubuntu-latest
    container:
      image: debian:buster
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 15
