name: macOS VM Workflow
on: [workflow_dispatch]
jobs:
  vm:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 15
