name: tmate session

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup tmate session
      run: |
        sudo apt-get update
        sudo apt-get install -y tmate
        tmate -S /tmp/tmate.sock new-session -d
        tmate -S /tmp/tmate.sock wait tmate-ready
        TMATE_CONNECT=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
        echo "tmate connection: $TMATE_CONNECT"
        echo "::set-output name=tmate_connect::$TMATE_CONNECT"
      id: tmate

    - name: Show tmate connection 1
      run: echo "${{ steps.tmate.outputs.tmate_connect }}"

    - name: Show tmate connection 2
      run: echo ${{ steps.tmate.outputs.tmate_connect }}

    - name: Show tmate connection 3
      run: |
        echo "The tmate connection string is:"
        echo ${{ steps.tmate.outputs.tmate_connect }}
