name: Ubuntu 20.04 VM Workflow
on: [workflow_dispatch]
jobs:
  vm:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 15
